version: '3.8'

networks:
  schedule-network:
    driver: bridge

services:

  app:
    build: .
    command: python app.py
    ports:
      - "8080:5000"
    environment:
      - MODE=comfort
      - POPULATION_SIZE=100
      - MAX_ITERATIONS=500
      - MUTATION_RATE=0.1
      - APP_MODE=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./output:/app/output
    networks:
      - schedule-network
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - schedule-network
    restart: unless-stopped
